### ISSUE TITLE
Using Hydranet on Kitti dataset

### ISSUE THREAD

**Issue by MarSpit** [adithyagaurav/Multi_Task_Learning#1]
Hi, 
I would like to use your pretrained Hydranet for depth prediction on the Kitti dataset, as you did in your paper. Unfortunately, in the repo I can only find the files for the NYU-D dataset. It would be great if you could also provide the code (e.g. dataloader and pretrained neural net) you used when you did the investigations regarding Kitti. 
Many thanks!

**Comment by adithyagaurav** [comment]
Hi,

Thanks for reaching out. In the repo I think you will find a file
ExpKITTI_joint.ckpt
<https://github.com/adithyagaurav/Multi_Task_Learning/blob/master/ExpKITTI_joint.ckpt>,
these are the weights for this model trained on KITTI dataset, in fact if
you clone the repo and execute "python3 inference_image.py", the script
will automatically load the weights on the model and provide the output.

What you do need for a successful run however is the RGB Image data, I have
tested on the images that you can find in attachments. I will add some
debug code to the inference scripts which I think will improve the clarity
of the code

Regards,
Adithya
 data.zip
<https://drive.google.com/file/d/1PopR2kPhVTPkOD_8XFhNKx7hetfS0cNj/view?usp=drive_web>

**Comment by MarSpit** [comment]
Great, many thanks for the immediate help. I got it going on Kitti 👍 
Best regards 
Marius

**Comment by adithyagaurav** [comment]
Glad to help

The training on Kitti Dataset is trickier though. You see there's a
fundamental problem in Kitti, that there are only like 200 segmentation
data points. While there are many many more data points for depth
prediction.

This creates a big training problem when working with Kitti. The authors in
the paper I have referenced used Knowledge Distillation to solve this
problem you should check that, I am still looking in to how to achieve that
however.

Thankfully they provided weights of network so I could test the model. So
training part at this time is only available for NYU-D dataset.

Regards
